name: Run Tests

on:
  push:
    branches:
      - v1  # Déclenchement uniquement sur les commits dans la branche "v1"

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Version de Python à utiliser

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r v1/requirements.txt

    - name: Run Pytest
      env:
        PYTHONPATH: ./v1/src
      run: |
        cd v1 && python -m pytest tests/
